spring:
  datasource:
    initialization-mode: always
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}/${DATABASE_NAME:postgres}?currentSchema=public
    time-zone: UTC+3
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:p47KT02sl}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          time_zone: UTC
          batch_size: 5
        order_updates: true
        order_inserts: true
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.xml

  main:
    allow-bean-definition-overriding: true
  application:
    name: mmbp-server-side

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data: INFO
    ru.spb.devpractices: DEBUG

  file:
    name: /home/yboyko/logs/mb-app-server.log


